// Code generated by Slice Machine. DO NOT EDIT.
import dynamic from 'next/dynamic'

export const components = {
  frontpage_hero_slice: dynamic(() => import('./FrontpageHeroSlice')),
  project_banner: dynamic(() => import('./ProjectBannerSlice')),
  project_showcase_slice: dynamic(() => import('./ProjectShowcaseSlice')),
}
